URL = 'https://lfklzr5jsotrttsdjaymmzky7q0tlvtn.lambda-url.us-east-1.on.aws'
LOG_CENTRAL = '/dev/log_central'
LIMPAR_LOG_CENTRAL ='/dev/limpar_log_central'


REMOVER_TODOS_PROCESSOS = '/dev/remover_todos_processos'
PROCESSOS_INATIVOS = '/processos_inativos'
PROCESSOS_ATIVOS = '/processos_ativos'
INATIVAR_PROCESSO = '/inativar_processo'
ATIVAR_PROCESSO = '/ativar_processo'
INATIVAR_TODOS_PROCESSOS = '/inativar_todos_processos'
ATIVAR_TODOS_PROCESSOS = '/ativar_todos_processos'
ADICIONAR_ACAO_A_LISTA_DE_ERROS = '/adicionar_acao_a_lista_de_erros'
ACOES_EM_ERRO = '/acoes_em_erro'
REMOVER_ACAO_DA_LISTA_DE_ERROS ='/remover_acao_da_lista_de_erros'
REMOVER_TODAS_ACOES_DA_LISTA_DE_ERROS ='/remover_todas_acoes_da_lista_de_erros'
TODOS_PROCESSOS =  '/todos_processos'
VISUALIZAR_DOCUMENTO = '/visualizar_documento'

DADOS_DO_PROCESSO = '/dados_do_processo'
MODIFICAR_PROCESSO = '/modificar_processo'
CRIAR_PROCESSO = '/criar_processo'
EXCLUIR_PROCESSO = '/dev/excluir_processo'
ADICIONAR_DOCUMENTO_DO_PROCESSO = '/adicionar_documento_do_processo'
EXCLUIR_DOCUMENTO_DO_PROCESSO = '/dev/excluir_documento_do_processo'



ROTAS_GLOBAIS = [
    LOG_CENTRAL,
    LIMPAR_LOG_CENTRAL
]

ROTAS_DE_AMBIENTE =[
    REMOVER_TODOS_PROCESSOS,
    PROCESSOS_INATIVOS,
    PROCESSOS_ATIVOS,
    INATIVAR_TODOS_PROCESSOS,
    ATIVAR_TODOS_PROCESSOS,
    ACOES_EM_ERRO,
    ADICIONAR_ACAO_A_LISTA_DE_ERROS,
    REMOVER_ACAO_DA_LISTA_DE_ERROS, 
    REMOVER_TODAS_ACOES_DA_LISTA_DE_ERROS,
    TODOS_PROCESSOS
]


ROTAS_DE_PROCESSO = [
   DADOS_DO_PROCESSO,
   MODIFICAR_PROCESSO,
   INATIVAR_PROCESSO,
   ATIVAR_PROCESSO,
   EXCLUIR_PROCESSO,
   CRIAR_PROCESSO,
   VISUALIZAR_DOCUMENTO,
   ADICIONAR_DOCUMENTO_DO_PROCESSO,
   EXCLUIR_DOCUMENTO_DO_PROCESSO
]

ROTAS_DE_ESCRITA =[
    LIMPAR_LOG_CENTRAL,
    ADICIONAR_ACAO_A_LISTA_DE_ERROS,
    REMOVER_ACAO_DA_LISTA_DE_ERROS,
    REMOVER_TODOS_PROCESSOS,
    ADICIONAR_DOCUMENTO_DO_PROCESSO,
    EXCLUIR_DOCUMENTO_DO_PROCESSO,
    MODIFICAR_PROCESSO,
    CRIAR_PROCESSO,
    EXCLUIR_PROCESSO,
]

ROTAS_VALIDAS = ROTAS_GLOBAIS + ROTAS_DE_AMBIENTE + ROTAS_DE_PROCESSO 